import os
from openai import OpenAI
from dotenv import load_dotenv

# Load .env variables including OPENAI_API_KEY
load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def generate_message(prompt: str) -> str:
    """
    Send a prompt to the OpenAI API and return the generated response text.

    Args:
        prompt (str): The message prompt to send to the LLM.

    Returns:
        str: The response text generated by the OpenAI ChatCompletion.
    """
    response = client.chat.completions.create(
        model="gpt-3.5-turbo", messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content
